[2025-04-14 12:36:13,963](__post_init__) Проблема с подключением к серверу очереди: HTTPConnectionPool(host='192.168.124.1', port=32107): Max retries exceeded with url: /get_wplace?w=8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002071D6E04C0>: Failed to establish a new connection: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера'))
[2025-04-14 12:56:08,424](__post_init__) Проблема с подключением к серверу очереди: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
